version: "3"
services:
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgresdata:/data/postgres
    env_file:
      - postgres.env
    networks:
      - boilerplate

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:8080"
    volumes:
      - pgadmindata:/root/.pgadmin
    env_file:
      - postgres.env
    networks:
      - boilerplate
    links:
      - postgres:postgres

  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 80 --reload"
    ports:
      - "80:80"
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - boilerplate

volumes:
  postgresdata:
    driver: local
  pgadmindata:
    driver: local

networks:
  boilerplate:
    driver: bridge
