version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14.8-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgresdata:/data/postgres
    env_file:
      - postgres.env
    networks:
      - project1

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - pgadmindata:/root/.pgadmin
    env_file:
      - postgres.env
    networks:
      - project1
    links:
      - postgres:postgres

  project1:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - "80:80"
    depends_on:
      - postgres
      - pgadmin
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - project1

volumes:
  postgresdata:
    driver: local
  pgadmindata:
    driver: local

networks:
  project1:
    driver: bridge
