name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # workflow_run:
  #   workflows: ["Test and Publish Docker Image"]
  #   types:
  #     - completed

jobs:
  generate:
    name: Generate Documents
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Create and start virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Get Poetry cache files location
        id: poetry-cache
        run: echo "dir=$(poetry config cache-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Dependencies with Poetry
        run: poetry install

      - name: Generate Documentation
        run: bash scripts/documentation.sh

      - name: Commit Documentation Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add documentation/*
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update documentation"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          fi

  build:
    name: Build Docusaurus
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Change Directory to Documentation
        run: |
          cd documentation

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: documentation/yarn.lock

      - name: Install dependencies
        working-directory: documentation
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build

  deploy:
    name: Deploy to GitHub Pages
    needs: [generate, build]
    runs-on: ubuntu-latest
    steps:
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: shimpybansal
          user_email: shimpydbansal@gmail.com
